<a href="https://colab.research.google.com/github/gurramsantosh236/PythonPractice/blob/main/python_Learning_Week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello World")

Hello World


In [ ]:
x=[1,4,7,9]
print(type(x))
y=sum(x)
print(y)
for i,j in enumerate(x,start=1):
  print((f'Text index in the List{i}:{j}'))

<class 'list'>
21
Text index in the List1:1
Text index in the List2:4
Text index in the List3:7
Text index in the List4:9


In [ ]:
# Input/Output example
name=input("Enter your name: ")
print(f"Hello {name}")

Enter your name: SantoshKumar
Hello SantoshKumar


In [ ]:
#Reverse a String
name=input("Enter your name: ")
revStr=""
for i in name[::-1]:
  revStr+=i
  print(i,end="")

print(revStr)


Enter your name: Santoshkumar
ramukhsotnaSramukhsotnaS


In [ ]:
Name="SantoshKumar"
print(Name[::-1])

ramuKhsotnaS


In [ ]:
Name="SantoshKumar"
lenName=len(Name)
for i in range(lenName-1,-1,-1):
  print(Name[i],end="")

ramuKhsotnaS

In [ ]:
Name="SantoshKumar"
lenName=len(Name)
for i in Name[::-1]:
  print(i,end="")



ramuKhsotnaS

In [ ]:
Name="SantoshKumar"
lenName=len(Name)
while lenName>0:
  lenName-=1
  print(Name[lenName],end="")

ramuKhsotnaS

In [39]:
import numpy as np
l1=[1,2,3,4,5]
ar=np.array(l1)
print(f"Details of List:{l1}")

print(f"Details of Array:{ar}")

Details of List:[1, 2, 3, 4, 5]
Details of Array:[1 2 3 4 5]


In [40]:
#Create a 0-D array with value 42
import numpy as np

arr = np.array(42)

print(arr)

42


In [41]:
#Create a 1-D array containing the values 1,2,3,4,5:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [43]:
#Print the last element from the 2nd dim:


import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

print('Last element from 2nd dim: ', arr[1, -1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last element from 2nd dim:  10
