In [ ]:
print("Hello World")

Hello World


In [ ]:
x=[1,4,7,9]
print(type(x))
y=sum(x)
print(y)
for i,j in enumerate(x,start=1):
  print((f'Text index in the List{i}:{j}'))

<class 'list'>
21
Text index in the List1:1
Text index in the List2:4
Text index in the List3:7
Text index in the List4:9


In [ ]:
# Input/Output example
name=input("Enter your name: ")
print(f"Hello {name}")

Enter your name: SantoshKumar
Hello SantoshKumar


In [ ]:
#Reverse a String
name=input("Enter your name: ")
revStr=""
for i in name[::-1]:
  revStr+=i
  print(i,end="")

print(revStr)


Enter your name: Santoshkumar
ramukhsotnaSramukhsotnaS


In [ ]:
Name="SantoshKumar"
print(Name[::-1])

ramuKhsotnaS


In [ ]:
Name="SantoshKumar"
lenName=len(Name)
for i in range(lenName-1,-1,-1):
  print(Name[i],end="")

ramuKhsotnaS

In [ ]:
Name="SantoshKumar"
lenName=len(Name)
for i in Name[::-1]:
  print(i,end="")



ramuKhsotnaS

In [ ]:
Name="SantoshKumar"
lenName=len(Name)
while lenName>0:
  lenName-=1
  print(Name[lenName],end="")

ramuKhsotnaS

In [39]:
import numpy as np
l1=[1,2,3,4,5]
ar=np.array(l1)
print(f"Details of List:{l1}")

print(f"Details of Array:{ar}")

Details of List:[1, 2, 3, 4, 5]
Details of Array:[1 2 3 4 5]


In [40]:
#Create a 0-D array with value 42
import numpy as np

arr = np.array(42)

print(arr)

42


In [41]:
#Create a 1-D array containing the values 1,2,3,4,5:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [43]:
#Print the last element from the 2nd dim:


import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

print('Last element from 2nd dim: ', arr[1, -1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last element from 2nd dim:  10


In [45]:
import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr)
print(arr[1, 1, 0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
7


In [43]:
import numpy as np
l1=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
arr=np.array(l1)
print(arr)
print(arr.ndim)
print(arr.shape)
l2=np.nditer(arr)
print(l2)
newarr=[]
for i in l2:
  newarr.append(i)
  print(i)
print(newarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2
(3, 5)
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
[array(1), array(2), array(3), array(4), array(5), array(6), array(7), array(8), array(9), array(10), array(11), array(12), array(13), array(14), array(15)]


In [48]:
import numpy as np
l1=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
arr2=np.array(l1)
l2=sum(l1,[])
print(l2)
print(arr2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [54]:
l3=[]
for sublist in l1:
  for item in sublist:
    l3.append(item)
print(l3)

arr3=np.nditer(arr)
print(arr3)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


TypeError: array() missing required argument 'object' (pos 0)