In [ ]:
print("Hello World")

Hello World


In [ ]:
x=[1,4,7,9]
print(type(x))
y=sum(x)
print(y)
for i,j in enumerate(x,start=1):
  print((f'Text index in the List{i}:{j}'))

<class 'list'>
21
Text index in the List1:1
Text index in the List2:4
Text index in the List3:7
Text index in the List4:9


In [ ]:
# Input/Output example
name=input("Enter your name: ")
print(f"Hello {name}")

Enter your name: SantoshKumar
Hello SantoshKumar


In [ ]:
#Reverse a String
name=input("Enter your name: ")
revStr=""
for i in name[::-1]:
  revStr+=i
  print(i,end="")

print(revStr)


Enter your name: Santoshkumar
ramukhsotnaSramukhsotnaS


In [ ]:
Name="SantoshKumar"
print(Name[::-1])

ramuKhsotnaS


In [ ]:
Name="SantoshKumar"
lenName=len(Name)
for i in range(lenName-1,-1,-1):
  print(Name[i],end="")

ramuKhsotnaS

In [ ]:
Name="SantoshKumar"
lenName=len(Name)
for i in Name[::-1]:
  print(i,end="")



ramuKhsotnaS

In [ ]:
Name="SantoshKumar"
lenName=len(Name)
while lenName>0:
  lenName-=1
  print(Name[lenName],end="")

ramuKhsotnaS

In [39]:
import numpy as np
l1=[1,2,3,4,5]
ar=np.array(l1)
print(f"Details of List:{l1}")

print(f"Details of Array:{ar}")

Details of List:[1, 2, 3, 4, 5]
Details of Array:[1 2 3 4 5]


In [40]:
#Create a 0-D array with value 42
import numpy as np

arr = np.array(42)

print(arr)

42


In [41]:
#Create a 1-D array containing the values 1,2,3,4,5:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [43]:
#Print the last element from the 2nd dim:


import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

print('Last element from 2nd dim: ', arr[1, -1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last element from 2nd dim:  10


In [45]:
import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr)
print(arr[1, 1, 0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
7


In [43]:
import numpy as np
l1=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
arr=np.array(l1)
print(arr)
print(arr.ndim)
print(arr.shape)
l2=np.nditer(arr)
print(l2)
newarr=[]
for i in l2:
  newarr.append(i)
  print(i)
print(newarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2
(3, 5)
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
[array(1), array(2), array(3), array(4), array(5), array(6), array(7), array(8), array(9), array(10), array(11), array(12), array(13), array(14), array(15)]


In [12]:
import numpy as np
l1=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
arr2=np.array(l1)
l2=sum(l1,[])
print(l2)
print(arr2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [3]:
l3=[]
for sublist in l1:
  for item in sublist:
    l3.append(item)
print(l3)



[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [9]:
l3=[n for n in np.nditer(arr2)]
print(l3)

[array(1), array(2), array(3), array(4), array(5), array(6), array(7), array(8), array(9), array(10), array(11), array(12), array(13), array(14), array(15)]


In [13]:
l4=[item for item in l2 if item%2==0]
print(l4)

[2, 4, 6, 8, 10, 12, 14]


In [18]:
my_list = ["banana", "apple", "cherry"]
my_list.sort()
print(my_list)
my_list1 = ["banana", "apple", "cherry"]
sorted_list = sorted(my_list1)
print(sorted_list)

['apple', 'banana', 'cherry']
['apple', 'banana', 'cherry']


In [20]:
my_list = ["banana", "apple", "cherry"]
my_list.sort(reverse=True)
print(my_list)

['cherry', 'banana', 'apple']


In [22]:
my_list = ["banana", "apple", "cherry"]
my_list.sort(key=len)
print(my_list)

['apple', 'banana', 'cherry']


In [23]:
my_list = ["banana", "apple", "cherry"]
my_list.sort(key=str.lower)
print(my_list)

['apple', 'banana', 'cherry']


In [27]:
str1="SantoshKumar"
sorted_chars =sorted(str1)
print(sorted_chars )
sorted_str="".join(sorted_chars)
print(sorted_str)

['K', 'S', 'a', 'a', 'h', 'm', 'n', 'o', 'r', 's', 't', 'u']
KSaahmnorstu


In [39]:
l1=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
arr=np.array(l1)
print(arr.ravel)


<built-in method ravel of numpy.ndarray object at 0x7af5e6fba970>


### Explanation of the error in `l4` and corrected code:

The original code `l4=[item for item in l1 if item%2==0]` produced a `TypeError` because `l1` is a list of lists. When iterating `for item in l1`, each `item` is a sublist (e.g., `[1, 2, 3, 4, 5]`), and you cannot apply the modulo operator (`%`) to a list.

To get the even numbers from all sublists, you need to iterate through each sublist and then through each number within that sublist.

In [ ]:
# Corrected code using nested list comprehension
l4_corrected = [num for sublist in l1 for num in sublist if num % 2 == 0]
print(f"Corrected list of even numbers: {l4_corrected}")

# Alternatively, if you wanted to flatten the list first, then filter:
# First, flatten l1
flattened_l1 = [num for sublist in l1 for num in sublist]
# Then, filter for even numbers
l4_flattened_filtered = [num for num in flattened_l1 if num % 2 == 0]
print(f"Corrected list (flattened then filtered): {l4_flattened_filtered}")

In [ ]:
import numpy as np

# Assuming arr2 is defined from your previous operations, e.g.:
# arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

print(f"Original NumPy array (arr2):\n{arr2}")
print(f"Type of arr2: {type(arr2)}")

# Convert to a nested Python list (preserves dimensions)
nested_python_list = arr2.tolist()
print(f"\nConverted to nested Python list:\n{nested_python_list}")
print(f"Type of nested_python_list: {type(nested_python_list)}")

# Convert to a flat Python list (flattens all elements into a single list)
flat_python_list = arr2.flatten().tolist()
print(f"\nConverted to flat Python list:\n{flat_python_list}")
print(f"Type of flat_python_list: {type(flat_python_list)}")

In [ ]:
import numpy as np

# Assuming arr2 is still available from previous execution
print(f"Original NumPy array (arr2):\n{arr2}")

# Accessing elements from a 2D NumPy array (arr2):
print(f"\nFirst element of the first row (arr2[0,0]): {arr2[0,0]}")
print(f"Last element of the second row (arr2[1,-1]): {arr2[1,-1]}")
print(f"Element at row 2, column 3 (arr2[2,2]): {arr2[2,2]}") # Remember 0-based indexing

# If you have a list of 0-D NumPy arrays like l3:
# print(f"Original list l3: {l3}") # l3 is a list of numpy.ndarray objects

# Getting items (scalar values) from the 0-D numpy.ndarray objects in l3:
print(f"\nFirst item from l3 (using .item()): {l3[0].item()}")
print(f"Fifth item from l3 (using .item()): {l3[4].item()}")

# To get all items as a list of integers from l3:
all_items_from_l3 = [item.item() for item in l3]
print(f"All items from l3 as a Python list: {all_items_from_l3}")